import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import AuthContextProvider from "@/context/Auth/AuthContext";
import SideBar from "./(Component)/Sidebar/SideBar";
import TokenContextProvider from "@/context/Token/TokenContext";
import NotesContextProvider from "@/context/NotesContext/NotesContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <TokenContextProvider>
          <AuthContextProvider>
            <NotesContextProvider>
              <AppRouterCacheProvider>
                <ThemeProvider theme={theme}>
                  <SideBar />
                  {children}
                </ThemeProvider>
              </AppRouterCacheProvider>
            </NotesContextProvider>
          </AuthContextProvider>
        </TokenContextProvider>
      </body>
    </html>
  );
}
